#define RGFW_IMPLEMENTATION
#define RGFW_EXPORT
#define RGFW_OPENGL
#define RGFW_UNIX
#include "../3rd/RGFW.h"
#define GLAD_GL_IMPLEMENTATION
#include "../3rd/glad/gl.h"
#define STB_IMAGE_IMPLEMENTATION
#include "../3rd/stb_image.h"
